// src/Stubs/ReactView/Module/Breadcrumbs.jsx
import { Fragment } from 'react'
import { Link } from 'react-router-dom'
import { classFor } from 'innoboxrr-form-core'
import t from 'innoboxrr-i18n'

/**
 * Las migas de pan del modulo.
 *
 * La rama React no tenia migas en absoluto: las vistas Vue usaban un
 * <BreadcrumbsComponent> que no estaba definido en ningun paquete del
 * ecosistema —la aplicacion anfitriona tenia que registrarlo por su cuenta— y
 * en React no habia equivalente. Al generarlo dentro del modulo, las dos
 * ramas pintan lo mismo y ninguna depende de nada que no declare.
 *
 * @param {{ pages: { link: string, title: string }[] }} props
 */
export default function Breadcrumbs({ pages }) {
    return (
        <nav className={classFor('breadcrumb')} aria-label={t('Breadcrumb')}>

            {pages.map((page, index) => (
                <Fragment key={page.link ?? page.title}>

                    {index > 0 && (
                        <span className={classFor('breadcrumbSeparator')} aria-hidden="true">/</span>
                    )}

                    {/* El ultimo es donde esta el usuario: no es un enlace, y
                        se anuncia como la pagina actual. */}
                    {index === pages.length - 1 ? (
                        <span className={classFor('breadcrumbCurrent')} aria-current="page">
                            {page.title}
                        </span>
                    ) : (
                        <Link to={page.link} className={classFor('breadcrumbLink')}>
                            {page.title}
                        </Link>
                    )}

                </Fragment>
            ))}

        </nav>
    )
}

// src/Stubs/ModelView/Module/Breadcrumbs.vue
<template>

    <nav :class="classFor('breadcrumb')" :aria-label="t('Breadcrumb')">

        <template v-for="(page, index) in pages" :key="page.link ?? page.title">

            <span v-if="index > 0" :class="classFor('breadcrumbSeparator')" aria-hidden="true">/</span>

            <!-- El ultimo es donde esta el usuario: no es un enlace, y se
                 anuncia como la pagina actual. -->
            <span
                v-if="index === pages.length - 1"
                :class="classFor('breadcrumbCurrent')"
                aria-current="page">{{ page.title }}</span>

            <RouterLink
                v-else
                :to="page.link"
                :class="classFor('breadcrumbLink')">{{ page.title }}</RouterLink>

        </template>

    </nav>

</template>

<script setup>

    /**
     * Las migas de pan del modulo.
     *
     * Existe aqui, dentro del modulo generado, y no como componente global de
     * la aplicacion: hasta ahora las vistas Vue usaban un
     * <BreadcrumbsComponent> que no estaba definido en ningun paquete del
     * ecosistema, asi que el codigo generado solo compilaba si la aplicacion
     * anfitriona lo habia registrado por su cuenta, sin que ningun import ni
     * peerDependency lo dijera.
     */

    import { RouterLink } from 'vue-router'
    import { classFor } from 'innoboxrr-form-core'
    import t from 'innoboxrr-i18n'

    defineProps({
        /** @type {{ link: string, title: string }[]} */
        pages: {
            type: Array,
            required: true,
        },
    })

</script>
