// src/Stubs/ModelView/views/CreateView.vue
<template>
	<div>
		<breadcrumbs-component  
			:pages="[
				{ link: $router.resolve({ name: 'AdminPluralPascalCaseModelName' }).fullPath, title: 'PluralPascalCaseModelName'},
				{ link: $router.resolve({ name: 'AdminCreatePascalCaseModelName' }).fullPath, title: 'Crear PluralPascalCaseModelName'}
			]"/>	
		<div class="flex justify-center items-center mt-8">
			<div class="max-w-2xl w-full">
				<div class="card bg-white dark:bg-slate-600 border rounded-lg px-8 pt-6 pb-8 mb-4 dark:border-slate-800">
					<h2 class="text-4xl font-bold dark:text-white mb-6">
						Crear PluralPascalCaseModelName
					</h2>
					<create-form 
						@submit="formSubmit"/>
				</div>
			</div>
		</div>
	</div>
</template>

<script>
	import { getPolicy } from '@models/kebabcasemodelname'
	import CreateForm from '@models/kebabcasemodelname/forms/CreateForm.vue'

	export default {
		components: {
			CreateForm
		},
		emits: ['updateData'],
		mounted(){
			this.fetchCreatePolicy();
		},
		methods: {
			fetchCreatePolicy() {
				getPolicy('create').then( res => {
					if(!res.create) {
						// this.$router.push({name: "NotAuthorized" });
					}
                });
			},
			formSubmit(payload) {	
				this.$emit('updateData', payload);
				this.$router.push({
					name: "AdminShowPascalCaseModelName", 
					params: { 
						id: payload.id 
					} 
				});
			}
		}
	}
</script>

// src/Stubs/ReactView/views/CreateView.jsx
import { useEffect } from 'react'
import { useNavigate, useOutletContext } from 'react-router-dom'
import { buildPath } from 'innoboxrr-react-datatable'
import t from 'innoboxrr-i18n'

import CreateForm from '../forms/CreateForm.jsx'
import Breadcrumbs from '../../../components/Breadcrumbs.jsx'
import { getPolicy } from '../index'

export default function CreateView() {
    const navigate = useNavigate()
    const { onUpdateData } = useOutletContext() ?? {}

    useEffect(() => {
        getPolicy('create').then((policy) => {
            if (! policy.create) {
                // navigate('/not-authorized')
            }
        })
    }, [])

    const onCreated = (camelCaseModelName) => {
        onUpdateData?.(camelCaseModelName)

        navigate(buildPath('AdminShowPascalCaseModelName', { id: camelCaseModelName.id }))
    }

    const breadcrumbs = [
        {
            link: buildPath('AdminPluralPascalCaseModelName'),
            title: 'PluralPascalCaseModelName',
        },
        {
            link: buildPath('AdminCreatePascalCaseModelName'),
            title: t('Create PluralPascalCaseModelName'),
        },
    ]

    return (
        <div>
            <Breadcrumbs pages={breadcrumbs} />

            <div className="flex justify-center items-center mt-8">
                <div className="max-w-2xl w-full">
                    <div className="card bg-white dark:bg-slate-600 border rounded-lg px-8 pt-6 pb-8 mb-4 dark:border-slate-800">

                        <h2 className="text-4xl font-bold dark:text-white mb-6">
                            {t('Create PluralPascalCaseModelName')}
                        </h2>

                        <CreateForm onSubmit={onCreated} />

                    </div>
                </div>
            </div>
        </div>
    )
}
