// src/Stubs/ModelView/widgets/ModelProfile.vue
<template>

    <section v-if="record" class="fe-card">

        <header class="fe-toolbar">

            <div>
                <h2>{{ t('Details') }}</h2>
                <p class="fe-text-muted fe-text-sm">{{ t('Additional information') }}</p>
            </div>

            <span class="fe-toolbar-spacer" />

            <span class="fe-badge">ID: {{ record.id }}</span>

        </header>

        <dl class="fe-card-body">
            <div>
                <dt class="fe-text-muted fe-text-sm">{{ t('Created at') }}</dt>
                <dd>{{ record.created_at }}</dd>
            </div>
            <!-- Agrega mas campos aqui segun sea necesario -->
        </dl>

    </section>

</template>

<script setup>

    import { computed, onMounted, ref } from 'vue'
    import t from 'innoboxrr-i18n'

    import { showModel } from '../index'

    const props = defineProps({
        camelCaseModelName: {
            type: Object,
            default: null,
        },
        camelCaseModelNameId: {
            type: [Number, String],
            default: null,
        },
    })

    // La version anterior asignaba el resultado sobre el prop, lo que Vue
    // prohibe: el dato cargado vive en un ref propio.
    const fetched = ref(null)

    const record = computed(() => props.camelCaseModelName ?? fetched.value)

    onMounted(async () => {

        if (props.camelCaseModelName || ! props.camelCaseModelNameId) {
            return
        }

        fetched.value = await showModel(props.camelCaseModelNameId)

    })

</script>

// src/Stubs/ReactView/widgets/ModelProfile.jsx
import { useEffect, useState } from 'react'
import t from 'innoboxrr-i18n'

import { showModel } from '../index'

export default function ModelProfile({ camelCaseModelName = null, camelCaseModelNameId = null }) {
    // La version anterior de Vue asignaba el resultado sobre el prop, lo que
    // Vue prohibe y React ni siquiera permite: el dato cargado vive aparte.
    const [fetched, setFetched] = useState(null)

    const record = camelCaseModelName ?? fetched

    useEffect(() => {
        if (camelCaseModelName || ! camelCaseModelNameId) {
            return
        }

        let alive = true

        showModel(camelCaseModelNameId).then((loaded) => {
            if (alive) {
                setFetched(loaded)
            }
        })

        return () => {
            alive = false
        }
    }, [camelCaseModelName, camelCaseModelNameId])

    if (! record) {
        return null
    }

    return (
        <section className="fe-card">

            <header className="fe-toolbar">

                <div>
                    <h2>{t('Details')}</h2>
                    <p className="fe-text-muted fe-text-sm">{t('Additional information')}</p>
                </div>

                <span className="fe-toolbar-spacer" />

                <span className="fe-badge">ID: {record.id}</span>

            </header>

            <dl className="fe-card-body">
                <div>
                    <dt className="fe-text-muted fe-text-sm">{t('Created at')}</dt>
                    <dd>{record.created_at}</dd>
                </div>
                {/* Agrega mas campos aqui segun sea necesario */}
            </dl>

        </section>
    )
}
