// src/Stubs/ReactView/views/AdminView.jsx
import { useCallback, useState } from 'react'
import { Outlet, useMatches } from 'react-router-dom'
import { buildPath } from 'innoboxrr-react-datatable'

import DataTable from '../widgets/DataTable.jsx'
import Breadcrumbs from '../../../components/Breadcrumbs.jsx'

export default function AdminView() {
    const matches = useMatches()

    // El indice es la ruta hoja cuando no hay ninguna hija montada.
    const isIndex = matches.at(-1)?.id === 'AdminPluralPascalCaseModelName'

    // Forzar el remontaje del datatable es la forma de recargarlo tras una
    // alta o una baja hecha en una vista hija.
    const [crudKey, setCrudKey] = useState(0)

    const refresh = useCallback(() => setCrudKey((key) => key + 1), [])

    const breadcrumbs = [
        {
            link: buildPath('AdminPluralPascalCaseModelName'),
            title: 'PluralPascalCaseModelName',
        },
    ]

    return (
        <div id="AdminPluralPascalCaseModelNameWrapper">

            {isIndex ? (
                <div className="uk-section uk-section-xsmall">
                    <Breadcrumbs pages={breadcrumbs} />

                    <DataTable key={crudKey} hideColumns={[]} />
                </div>
            ) : (
                <Outlet context={{ onUpdateData: refresh }} />
            )}

        </div>
    )
}

// src/Stubs/ModelView/views/AdminView.vue
<template>

    <div id="AdminPluralPascalCaseModelNameWrapper">

        <div v-if="isIndex" class="uk-section uk-section-xsmall">

            <Breadcrumbs :pages="breadcrumbs" />

            <DataTable
                :show-title="false"
                :hide-columns="hideColumns"
                :key="crudKey" />

        </div>

        <div v-else>
            <RouterView @update-data="refresh" />
        </div>

    </div>

</template>

<script setup>

    import { computed, ref } from 'vue'
    import { RouterView, useRoute, useRouter } from 'vue-router'

    import DataTable from '../widgets/DataTable.vue'

    import Breadcrumbs from '../../../components/Breadcrumbs.vue'

    const route = useRoute()
    const router = useRouter()

    // Forzar el remontaje del datatable es la forma de recargarlo tras una
    // alta o una baja hecha en una vista hija.
    const crudKey = ref(0)

    const refresh = () => crudKey.value++

    const isIndex = computed(() => route.name === 'AdminPluralPascalCaseModelName')

    const hideColumns = computed(() => [])

    const breadcrumbs = computed(() => [
        {
            link: router.resolve({ name: 'AdminPluralPascalCaseModelName' }).fullPath,
            title: 'PluralPascalCaseModelName',
        },
    ])

</script>
