// src/Stubs/ReactView/forms/EditForm.jsx
import { useEffect, useRef, useState } from 'react'
import JSValidator from 'innoboxrr-js-validator'
import t from 'innoboxrr-i18n'
import {
    ButtonComponent,
    TextInputComponent,
//import_more_components//
} from 'innoboxrr-react-form-elements'

import { usePascalCaseModelNameStore } from '../store'

export default function EditForm({
    formId = 'editPascalCaseModelNameForm',
    camelCaseModelNameId,
//props//
    onSubmit,
}) {
    const fetchOne = usePascalCaseModelNameStore((state) => state.fetchOne)
    const update = usePascalCaseModelNameStore((state) => state.update)

    const [disabled, setDisabled] = useState(false)
    const validator = useRef(null)

    const [form, setForm] = useState({
//form_fields//
    })

    const setField = (field, value) => setForm((current) => ({ ...current, [field]: value }))

    useEffect(() => {
        let alive = true

        const load = async () => {
            const camelCaseModelName = await fetchOne(camelCaseModelNameId)

            if (! alive) {
                return
            }

            // Solo se rellenan las claves que el formulario declara; asi un
            // campo nuevo en la API no se cuela en el payload de
            // actualizacion.
            setForm((current) => Object.fromEntries(
                Object.keys(current).map((field) => [
                    field,
                    camelCaseModelName[field] !== undefined ? camelCaseModelName[field] : current[field],
                ])
            ))

            validator.current = new JSValidator(formId).init()
            validator.current.status = true
        }

        load()

        return () => {
            alive = false
        }
    }, [camelCaseModelNameId, fetchOne, formId])

    const handleSubmit = async (event) => {
        event.preventDefault()

        if (! validator.current?.status) {
            return
        }

        setDisabled(true)

        try {

            onSubmit?.(await update(camelCaseModelNameId, {
//submit_data//
            }))

        } catch (error) {

            if (error.response?.status === 422) {
                validator.current.appendExternalErrors(error.response.data.errors)
            }

        } finally {

            setDisabled(false)

        }
    }

    return (
        <form id={formId} onSubmit={handleSubmit}>

{/* Add more inputs */}

            <ButtonComponent
                disabled={disabled}
                value={t('Update')} />

        </form>
    )
}

// src/Stubs/ModelView/forms/EditForm.vue
<template>

    <form :id="formId" @submit.prevent="onSubmit">

<!-- Add more inputs -->

        <ButtonComponent
            :disabled="disabled"
            :value="t('Update')" />

    </form>

</template>

<script setup>

    import { onMounted, reactive, ref } from 'vue'
    import JSValidator from 'innoboxrr-js-validator'
    import t from 'innoboxrr-i18n'
    import {
        ButtonComponent,
        TextInputComponent,
//import_more_components//
    } from 'innoboxrr-form-elements'

    import { usePascalCaseModelNameStore } from '../store'

    const props = defineProps({
        formId: {
            type: String,
            default: 'editPascalCaseModelNameForm',
        },
        camelCaseModelNameId: {
            type: [Number, String],
            required: true,
        },
//props//
    })

    const emit = defineEmits(['submit'])

    const store = usePascalCaseModelNameStore()

    const disabled = ref(false)
    const validator = ref(null)

    const form = reactive({
//form_fields//
    })

    onMounted(async () => {

        const camelCaseModelName = await store.fetchOne(props.camelCaseModelNameId)

        // Solo se rellenan las claves que el formulario declara; asi un campo
        // nuevo en la API no se cuela en el payload de actualizacion.
        Object.keys(form).forEach((field) => {
            if (camelCaseModelName[field] !== undefined) {
                form[field] = camelCaseModelName[field]
            }
        })

        validator.value = new JSValidator(props.formId).init()
        validator.value.status = true

    })

    const onSubmit = async () => {

        if (! validator.value?.status) {
            return
        }

        disabled.value = true

        try {

            emit('submit', await store.update(props.camelCaseModelNameId, {
//submit_data//
            }))

        } catch (error) {

            if (error.response?.status === 422) {
                validator.value.appendExternalErrors(error.response.data.errors)
            }

        } finally {

            disabled.value = false

        }

    }

</script>
